### PR TITLE
enable tests again now that AVA 0.4.0 is out

### PR DESCRIPTION
**Pull request by sindresorhus**

### CODE REVIEW

**Comment by sindresorhus** [comment]
@floatdrop Any idea why AVA 0.4.0 is failing in Node.js 0.10? https://travis-ci.org/sindresorhus/pageres/jobs/89816347#L302

**Comment by floatdrop** [comment]
@sindresorhus since polyfills is disabled these should be fixed:

- `get-stream` https://github.com/sindresorhus/get-stream/blob/master/index.js#L5
- All `pify` calls without polyfills (https://github.com/floatdrop/pageres/blob/master/lib/util.js#L27, https://github.com/floatdrop/pageres/blob/master/lib/util.js#L43, https://github.com/floatdrop/pageres/blob/master/lib/util.js#L66, https://github.com/floatdrop/pageres/blob/master/lib/util.js#L73)

**Comment by sindresorhus** [comment]
Ah, I was sure it was something with AVA...

**Comment by sindresorhus** [comment]
Thanks for looking into it.

**Comment by floatdrop** [comment]
@sindresorhus you're welcome. This is what I was fearing, when talking about leaking polyfills from babel in tests ;)

**Comment by sindresorhus** [comment]
@floatdrop Yeah, point taken :p

**Comment by sindresorhus** [comment]
Actually, I now remembered that we dropped Node.js 0.10 support in Pageres v3.0.0, but I seem to have forgotten about updating travis file...

**Pull request merged**
