### PR TITLE
Add support for data URI

### LINKED ISSUE #254: Support for data URIs
When using a data URI as a pageres source (`data:text/html;base64,PGgxPkZPTzwvaDE+`), pageres generates a white, empty image file.

Is it possible to get pageres to use data URIs? phatom has support for data uris afaik!

### PR DESCRIPTION
**Pull request by kevva**
So I tried this using a data URI but it didn't work due to `protocolify` prepending `http://` before the URL. This fixes that.

Will also need to be fixed in the CLI.

Fixes #254.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you document it?

**Comment by sindresorhus** [comment]
> So I tried this using a data URI but it didn't work due to protocolify prepending http:// before the URL.

That should already be fixed [a week ago](https://github.com/sindresorhus/prepend-http/commit/d225dcbbbb47065d3581ff47d521749b055e5a6d). See test that proves it: https://github.com/sindresorhus/protocolify/commit/1895c3784bd106868bfdbe788f3b2a5a1dbfab74

**Comment by kevva** [comment]
@sindresorhus, oh, it probably is then. I think I'll need to remove the `node_modules` dir.

**Comment by SamVerschueren** [comment]
Is this good for merge?

**Comment by sindresorhus** [comment]
Yup. Thanks Kevin :)

**Comment by sindresorhus** [comment]
This also needs to be documented in `pageres-cli`.

**Comment by sindresorhus** [comment]
And travis is failing now... Ugh.

**Comment by SamVerschueren** [comment]
Let's just run them again? Don't have clue why that happens...

**Comment by sindresorhus** [comment]
@SamVerschueren I tried to rerun them. Same result.

**Comment by SamVerschueren** [comment]
If I change [this](https://github.com/sindresorhus/pageres/blob/master/test/test.js#L46) line to `github.com` instead of `yeoman.io`, it works. I have no clue where that IP is coming from to be honest `66.96.149.32`.

**Comment by sindresorhus** [comment]
@SamVerschueren Change it :)

**Comment by SamVerschueren** [comment]
@sindresorhus After pushing it, I noticed it failing on Travis-CI. Ran it again on my system, same error. Changed some bits and bytes and after a while the original tests started to pass. Couldn't get them failing.

So I digged a little deeper and found out that `got` (which is the origin of the error) is used by the `w3counter` and `viewport-list` packages. And it happens to be that the IP address of `viewportsizes.com` is `66.96.149.32`. So my best bet is that `viewportsizes.com` has some server issues at the moment.

**Comment by kevva** [comment]
@SamVerschueren, yup, looks like their site is down too.

**Comment by sindresorhus** [comment]
@kevva That site has been very unstable. Maybe you can add an additional API to your module that just get's the data from a scraped JSON file included in the package? (You could have it update the JSON file on publish). Kinda silly to be network bound for a list of ~200 entries that doesn't change that often.

**Comment by SamVerschueren** [comment]
@kevva will do a PR

**Comment by sindresorhus** [comment]
Same applies to [`get-res`](https://www.npmjs.com/package/get-res).

Actually, I would just do a major release and drop the live capability. It doesn't change that often. Better to just have both offline by default.

**Comment by kevva** [comment]
@SamVerschueren, great :+1:

@sindresorhus, yeah. Can just have a prepublish script and update it once a month or so.

**Pull request merged**
