### PR TITLE
WIP Typescript rewrite - Closes #336

### LINKED ISSUE #336: Rewrite in TypeScript
I originally rewrote it in Flow to get a feel for it. These days I only use TypeScript, so I would prefer to make this be in TypeScript too.

PR welcome if you want the challenge.

### PR DESCRIPTION
**Pull request by joshghent**
Wanted to submit the PR so you can track the work. I'm am still going through this. Hopefully will have it done today but there is a fair bit to do.

So far I have
- Added tslint with the xo config
- Add @types dependancies

Currently I am going through the main lib file and aiming to get it to build so we can start testing

### CODE REVIEW

**Comment by sindresorhus** [comment]
There seems to be some overlap in work here => #339

**Comment by joshghent** [comment]
@sindresorhus Ah yes that is a shame, I see his is currently building too. Tell ya what, if you get his work merged in then I can work on porting the test suite to typescript 👍

**Comment by sindresorhus** [comment]
Yeah, sorry about that. I know you commented about working on this first, but usually if someone doesn't do anything about an issue in a month, it usually means they will never, so I understand why he still decided to do it. Would you be willing to help review https://github.com/sindresorhus/pageres/pull/339? I'm gonna go with that one as he's a first-time TS user, so he needs to practice the most ;)

**Comment by joshghent** [comment]
@sindresorhus No worries! It's not your fault at all. Yeah I don't blame the guy, I was a bit slow with getting round to this 😅 Yes I'll give that a review, I agree - I already use TS daily so good to get first time users learning!

**Pull request closed without merging**
