### PR TITLE
Use async functions in the tests

### PR DESCRIPTION
**Pull request by SamVerschueren**
First part of asyncifying the test file. I have some trouble promisifying the stream pipes. Any help would be appreciated.

-

Part of #213.

### CODE REVIEW

**Comment by SamVerschueren** [comment]
I tried it with `get-stream`.

```js
test('crop image using the `crop` option', async t => {
	const streams = await new Pageres({ crop: true }).src('http://todomvc.com', ['1024x768']).run();

	t.is(streams[0].filename, 'todomvc.com-1024x768-cropped.png');

	const data = await getStream(streams[0]);

	const size = imageSize(data);
	t.is(size.width, 1024);
	t.is(size.height, 768);
});
```

Which results in the following error: `Path must be a string without null bytes.`

**Comment by sindresorhus** [comment]
> Which results in the following error: Path must be a string without null bytes.

`imageSize` expects a buffer, so you need to use `getStream.buffer()`.

> Als not really sure why your commit is popping up in my PR.

Try rebasing from master.

**Comment by SamVerschueren** [comment]
Oh boy, making things more worse here :s. My branch was behind so I synchronized my fork with the original repo and this is the result. Any tips? If not, will just start over with a fresh fork and copy-paste my changes. It's not that much.

Sorry for the trouble...

**Comment by sindresorhus** [comment]
Create a new branch from master, cherry pick the first commit from this branch into it, force push from that branch to this remote branch of this PR.

**Comment by SamVerschueren** [comment]
Ok thanks for the tip.

Still having your commit in my PR which is just really weird. And the `Merge branch 'master` of github.com:SamVerschueren/pageres` isn't very clean either.

**Comment by sindresorhus** [comment]
Thank you @SamVerschueren :) Looks so much better now.

**Comment by SamVerschueren** [comment]
Thank you for merging and helping! Again, sorry for the PR merge issues.

**Comment by kevva** [comment]
Sexy stuff.

**Pull request closed without merging**
